// Generated by https://quicktype.io
//
// To change quicktype's target language, run command:
//
//   "Set quicktype target language"

export interface Categories {
	trivia_categories: TriviaCategory[];
}

export interface TriviaCategory {
	id: number;
	name: string;
}
